[package]
name = "rustbot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
reqwest = { version = "0.11.25", features = ["json"] }
serde_json = "1.0.114"
serenity = "0.12.1"
tempfile = "3.10.1"
sysinfo = "0.30.7"
tokio = { version = "1.36.0", features = ["macros", "signal", "rt-multi-thread"] }
uptime_lib = "0.3.0"
serde = "1.0.197"

[[bin]]
name = "rustbot"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
strip = true
