[package]
name = "rustbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.7"
serenity = "0.12.0"
tokio = { version = "1.34.0", features = ["macros", "signal", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[[bin]]
name = "rustbot"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
