[package]
name = "rustbot"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "cmds",
  "events",
  "jobs",
  "library",
  "tsclient"
]

[workspace.dependencies]
cargo_toml = "0.21.0"
poise = "0.6.1"
regex = "1.11.1"
serde = "1.0.216"
rand = "0.8.5"
sysinfo = "0.33.0"
time = "0.3.37"
uptime_lib = "0.3.1"
tokio = { version = "1.42.0", features = ["macros", "signal", "rt-multi-thread"] }
reqwest = { version = "0.12.9", features = ["native-tls-vendored"] }
rustbot_lib = { path = "library" }

[dependencies]
poise = { workspace = true }
rustbot_cmds = { path = "cmds" }
rustbot_events = { path = "events" }
rustbot_lib = { workspace = true }
rustbot_tokens = { path = "tsclient" }
tokio = { workspace = true }

[patch.crates-io]
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }

[features]
production = ["rustbot_lib/production", "rustbot_events/production"]
not_ready = ["rustbot_lib/not_ready"]

[[bin]]
name = "rustbot"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 2
debug = false
strip = true
