[package]
name = "rustbot"
version = "0.1.0"
edition = "2021"

[dependencies]
bb8 = "0.8.5"
bb8-postgres = "0.8.1"
cargo_toml = "0.20.4"
once_cell = "1.19.0"
poise = "0.6.1"
regex = "1.10.6"
sysinfo = "0.32.0"
tokenservice-client = { version = "0.4.0", registry = "gitea" }
tokio = { version = "1.39.2", features = ["macros", "signal", "rt-multi-thread"] }
tokio-postgres = "0.7.11"
uptime_lib = "0.3.1"

[features]
production = []

[[bin]]
name = "rustbot"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 2
debug = false
strip = true
