[package]
name = "rustbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poise = "0.5.7"
reqwest = "0.11.23"
serde_json = "1.0.108"
serenity = "0.12.0"
tempfile = "3.9.0"
tokio = { version = "1.35.1", features = ["macros", "signal", "rt-multi-thread"] }

[[bin]]
name = "rustbot"
path = "src/main.rs"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false
