# trailing comma in arrays
always_trailing_comma = true

# trailing comma when multi-line
multiline_trailing_comma = true

# remove all the spacing inside the array
compact_arrays = false

# remove all the spacing inside the object
compact_inline_tables = false

# Windows EOF style
crlf = false

trailing_newline = false
space_around_eq = true
allowed_blank_lines = 1
