[package]
name = "rustbot_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo_toml = { workspace = true }
poise = { workspace = true }
tokenservice-client = { workspace = true }
tokio = { workspace = true }

[features]
production = []
not_ready = []
