[package]
name = "rustbot_tokens"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = { workspace = true }
tokenservice-client = { version = "0.4.2", registry = "gitea" }
tokio = { workspace = true }
