[package]
name = "rustbot_events"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = { workspace = true }
rustbot_lib = { workspace = true }

[features]
production = ["rustbot_lib/production"]
not_ready = ["rustbot_lib/not_ready"]
